### PR TITLE
[new] components switch, input, input_label, menu_item and chip

### PR DESCRIPTION
**Pull request by marceloakira**
Hi @williamneto!

Thanks for your great work! I am using your components in a [NLP tool called keyphrase curation](https://gitlab.com/ivato/argument-mapping/keyphrase_curation) but I need some components like:  switch, input, input_label, menu_item and chip. That's the purpose of this PR.

Thank you!
Marcelo

### CODE REVIEW

**Review by Archmonger — CHANGES_REQUESTED** [review]
You need to add the new components to the `readme.md`.

**Comment by marceloakira** [comment]
Done!

**Comment by williamneto** [comment]
Thanks for the contribution @marceloakira !

**Comment by marceloakira** [comment]
Happy to help.

**Pull request merged**
